config/routes.rb
MeetingsSystem::Application.routes.draw do
  get "pages/forside"

  resources :deltageres

  resources :agendas

  resources :meetings

  root :to => 'pages#forside'

end

app/models/agenda.rb
# encoding: UTF-8
class NewValidator < ActiveModel::Validator

  def validate(tal)
    @fejl = true
    if tal.meetingnr.to_f.to_s.ends_with? ".0"
      @fejl = false
    end
    if @fejl
      tal.errors[:meetingnr] << " af lige møde nummeret skal være et helt tal"
    end
  end

  def validate(text)
    @mistake = true
    if text.beskrivelse.length > 10
      @mistake = false
    end
    if @mistake
      text.errors[:beskrivelse] << "10 tegn mindst"
    end
  end
end


class Agenda < ActiveRecord::Base
  belongs_to :meeting
  validates :punktnavn, :presence => true
  validates :meetingnr, :punktnr, :numericality => {:greater_than_or_equal_to => 0.01}
  validates_with NewValidator
end

app/models/deltagere.rb
# encoding: UTF-8

class AwesomeValidator < ActiveModel::Validator
  def validate(numbers)

    @wrong = true
    if numbers.meetingnr.to_f.to_s.ends_with? ".0"
      @wrong = false
    end
    if @wrong
      numbers.errors[:meetingnr] << "møde nummeret skal være et helt tal"
    end
  end
 end

class Deltagere < ActiveRecord::Base
  validates :meetingnr, :numericality => true
  validates_with AwesomeValidator
end

app/models/meeting.rb
# encoding: UTF-8
class MyValidator2 < ActiveModel::Validator

  def validate(tal)
      @fejl = true

      if tal.navn.to_f == 0.0
        @fejl = false
      end

      if @fejl
        tal.errors[:navn] << 'Navn skal bestå af bogstaver'
      end
    end
end

class Meeting < ActiveRecord::Base
  has_many :agendas, :dependent => :destroy
  validates_with MyValidator2
  validates :kl, :numericality => true
  validates :nr, :numericality => {:greater_than_or_equal_to => 1}
  validates :dato, :sted, :navn, :presence => true

end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  # GET /agendas
  # GET /agendas.json
  def index
    @agendas = Agenda.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @agendas }
    end
  end

  # GET /agendas/1
  # GET /agendas/1.json
  def show
    @agenda = Agenda.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @agenda }
    end
  end

  # GET /agendas/new
  # GET /agendas/new.json
  def new
    @agenda = Agenda.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @agenda }
    end
  end

  # GET /agendas/1/edit
  def edit
    @agenda = Agenda.find(params[:id])
  end

  # POST /agendas
  # POST /agendas.json
  def create
    @agenda = Agenda.new(params[:agenda])

    respond_to do |format|
      if @agenda.save
        format.html { redirect_to @agenda, notice: 'Agenda was successfully created.' }
        format.json { render json: @agenda, status: :created, location: @agenda }
      else
        format.html { render action: "new" }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /agendas/1
  # PUT /agendas/1.json
  def update
    @agenda = Agenda.find(params[:id])

    respond_to do |format|
      if @agenda.update_attributes(params[:agenda])
        format.html { redirect_to @agenda, notice: 'Agenda was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendas/1
  # DELETE /agendas/1.json
  def destroy
    @agenda = Agenda.find(params[:id])
    @agenda.destroy

    respond_to do |format|
      format.html { redirect_to agendas_url }
      format.json { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/deltageres_controller.rb
class DeltageresController < ApplicationController
  # GET /deltageres
  # GET /deltageres.json
  def index
    @deltageres = Deltagere.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deltageres }
    end
  end

  # GET /deltageres/1
  # GET /deltageres/1.json
  def show
    @deltagere = Deltagere.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deltagere }
    end
  end

  # GET /deltageres/new
  # GET /deltageres/new.json
  def new
    @deltagere = Deltagere.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deltagere }
    end
  end

  # GET /deltageres/1/edit
  def edit
    @deltagere = Deltagere.find(params[:id])
  end

  # POST /deltageres
  # POST /deltageres.json
  def create
    @deltagere = Deltagere.new(params[:deltagere])

    respond_to do |format|
      if @deltagere.save
        format.html { redirect_to @deltagere, notice: 'Deltagere was successfully created.' }
        format.json { render json: @deltagere, status: :created, location: @deltagere }
      else
        format.html { render action: "new" }
        format.json { render json: @deltagere.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /deltageres/1
  # PUT /deltageres/1.json
  def update
    @deltagere = Deltagere.find(params[:id])

    respond_to do |format|
      if @deltagere.update_attributes(params[:deltagere])
        format.html { redirect_to @deltagere, notice: 'Deltagere was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @deltagere.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deltageres/1
  # DELETE /deltageres/1.json
  def destroy
    @deltagere = Deltagere.find(params[:id])
    @deltagere.destroy

    respond_to do |format|
      format.html { redirect_to deltageres_url }
      format.json { head :ok }
    end
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def forside
  end

end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deltageres_helper.rb
module DeltageresHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/agendas/_form.html.erb
<%= form_for(@agenda) do |f| %>
  <% if @agenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agenda.errors.count, "error") %> prohibited this agenda from being saved:</h2>

      <ul>
      <% @agenda.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meetingnr %><br />
    <%= f.text_field :meetingnr %>
  </div>
  <div class="field">
    <%= f.label :punktnr %><br />
    <%= f.text_field :punktnr %>
  </div>
  <div class="field">
    <%= f.label :punktnavn %><br />
    <%= f.text_field :punktnavn %>
  </div>
  <div class="field">
    <%= f.label :beskrivelse %><br />
    <%= f.text_area :beskrivelse %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agendas/edit.html.erb
<h1>Editing agenda</h1>

<%= render 'form' %>

<%= link_to 'Show', @agenda %> |
<%= link_to 'Back', agendas_path %>

app/views/agendas/index.html.erb
<h1>Listing agendas</h1>

<table>
  <tr>
    <th>Meetingnr</th>
    <th>Punktnr</th>
    <th>Punktnavn</th>
    <th>Beskrivelse</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @agendas.each do |agenda| %>
  <tr>
    <td><%= agenda.meetingnr %></td>
    <td><%= agenda.punktnr %></td>
    <td><%= agenda.punktnavn %></td>
    <td><%= agenda.beskrivelse %></td>
    <td><%= link_to 'Show', agenda %></td>
    <td><%= link_to 'Edit', edit_agenda_path(agenda) %></td>
    <td><%= link_to 'Destroy', agenda, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Agenda', new_agenda_path %>

app/views/agendas/new.html.erb
<h1>New agenda</h1>

<%= render 'form' %>

<%= link_to 'Back', agendas_path %>

app/views/agendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Meetingnr:</b>
  <%= @agenda.meetingnr %>
</p>

<p>
  <b>Punktnr:</b>
  <%= @agenda.punktnr %>
</p>

<p>
  <b>Punktnavn:</b>
  <%= @agenda.punktnavn %>
</p>

<p>
  <b>Beskrivelse:</b>
  <%= @agenda.beskrivelse %>
</p>


<%= link_to 'Edit', edit_agenda_path(@agenda) %> |
<%= link_to 'Back', agendas_path %>

app/views/deltageres/_form.html.erb
<%= form_for(@deltagere) do |f| %>
  <% if @deltagere.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deltagere.errors.count, "error") %> prohibited this deltagere from being saved:</h2>

      <ul>
      <% @deltagere.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meetingnr %><br />
    <%= f.text_field :meetingnr %>
  </div>
  <div class="field">
    <%= f.label :navn %><br />
    <%= f.select(:navn, raw("<option value='jvn'>Joel</option><option value='mkl'>Mikkel</option> <option value'nsl'>Nicolai</option>")) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deltageres/edit.html.erb
<h1>Editing deltagere</h1>

<%= render 'form' %>

<%= link_to 'Show', @deltagere %> |
<%= link_to 'Back', deltageres_path %>

app/views/deltageres/index.html.erb
<h1>Listing deltageres</h1>

<table>
  <tr>
    <th>Meetingnr</th>
    <th>Navn</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deltageres.each do |deltagere| %>
  <tr>
    <td><%= deltagere.meetingnr %></td>
    <td><%= deltagere.navn %></td>
    <td><%= link_to 'Show', deltagere %></td>
    <td><%= link_to 'Edit', edit_deltagere_path(deltagere) %></td>
    <td><%= link_to 'Destroy', deltagere, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deltagere', new_deltagere_path %>

app/views/deltageres/new.html.erb
<h1>New deltagere</h1>

<%= render 'form' %>

<%= link_to 'Back', deltageres_path %>

app/views/deltageres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Meetingnr:</b>
  <%= @deltagere.meetingnr %>
</p>

<p>
  <b>Navn:</b>
  <%= @deltagere.navn %>
</p>


<%= link_to 'Edit', edit_deltagere_path(@deltagere) %> |
<%= link_to 'Back', deltageres_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <body>
        <div class="container-fluid">
            <div class="sidebar" style="background-color: #848484">
              <center>
                <h4>Mikia Holding A/S</h4>
                <br/>
                <br/>
                <b>Kontakt information</b>
                <%= image_tag 'logo.jpg' %>
                <br/>
                <br/>
                <p>
                    <b>Postadresse</b> <br/>
                    C.F.Møllers Alle 60 4 tv <br/> 2300 København S  <br/>
                </p>
                <br/>
                <p>
                  <b>Bank og CVR <b></b> <br/>
                  BANK: Nordea <br/>
                  Regnr: 2217 <br/> <br/>
                  Konto: 4382 554 219 <br/>  <br/>
                </p>
                <p>
                  <b>Mailadresse</b>
                  nsl@mikiaholding.dk
                </p>
                <br/>
                <p>
                  <b>Telefon nummer</b> <br/>
                  Nicolaj Lindtners mobiltelefon: <br/>
                  3142 5626          <br/>
                </p>
              </center>
            </div>
            <div class="content">
                <head>
                    <title>MeetingsSystem</title>
                    <%= stylesheet_link_tag    "application" %>
                    <%= javascript_include_tag "application" %>
                    <%= csrf_meta_tags %>
                </head>

                <body style="padding-top: 100px; background-color: #BDBDBD; height: 700px;">
                    <div style="z-index: 5;" class="topbar-wrapper">
                        <div data-dropdown="dropdown" class="topbar">
                            <div class="topbar-inner" style="color: #FF8C00;">
                                <div class="container">
                                    <ul class="pills">
                                        <li class="active"><%= link_to 'Forsiden', root_path %></li>
                                        <li><%= link_to 'Møder', meetings_path %></li>
                                        <li><%= link_to 'Agendaer', agendas_path %></li>
                                        <li><%= link_to 'Deltagere', deltageres_path %></li>
                                    </ul>
                                </div>
                            </div><!-- /topbar-inner -->
                        </div><!-- /topbar -->
                    </div>


                    <%= yield %>


                    <footer class="footer">
                        <div class="container">
                            <p class="pull-right">Joel og Mikkel er for vilde</p>
                            <p>
                                Lavet til Mikia holdig AS "A Company in Progress"
                            </p>
                        </div>
                    </footer>
                </body>
            </div>
        </div>
    </body>
</html>

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nr %><br />
    <%= f.text_field :nr %>
  </div>
  <div class="field">
    <%= f.label :dato %><br />
    <%= f.text_field :dato %>
  </div>
  <div class="field">
    <%= f.label :sted %><br />
    <%= f.text_field :sted %>
  </div>
  <div class="field">
    <%= f.label :kl %><br />
    <%= f.text_field :kl %>
  </div>
  <div class="field">
    <%= f.label :navn %><br />
    <%= f.text_field :navn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<h1>Listing meetings</h1>

<table>
  <tr>
    <th>Nr</th>
    <th>Dato</th>
    <th>Sted</th>
    <th>Kl</th>
    <th>Navn</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetings.each do |meeting| %>
  <tr>
    <td><%= meeting.nr %></td>
    <td><%= meeting.dato %></td>
    <td><%= meeting.sted %></td>
    <td><%= meeting.kl %></td>
    <td><%= meeting.navn %></td>
    <td><%= link_to 'Show', meeting %></td>
    <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
    <td><%= link_to 'Destroy', meeting, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>




<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nr:</b>
  <%= @meeting.nr %>
</p>

<p>
  <b>Dato:</b>
  <%= @meeting.dato %>
</p>

<p>
  <b>Sted:</b>
  <%= @meeting.sted %>
</p>

<p>
  <b>Kl:</b>
  <%= @meeting.kl %>
</p>

<p>
  <b>Navn:</b>
  <%= @meeting.navn %>
</p>


<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/pages/forside.html.erb
<div class="container">
    <div title="Default three column layout" class="row show-grid">
        <center><div class="span-one-third">
          <%=link_to 'Nyt Møde', new_meeting_path, :class =>'btn large primary'%><br/> <br/> <br/> <br/>
        </div></center>
        <center><div class="span-one-third">
          <%=link_to 'Nyt Agenda', new_agenda_path, :class =>'btn large primary'%>
        </div></center>
        <center><div class="span-one-third">
          <%=link_to 'Tilføj Deltagere', new_deltagere_path, :class =>'btn large primary'%>
        </div></center>

        <center><img src='meeting.jpeg' style="width:900px; height: 500px; border: solid black 1px;;" /></center>
    </div>
</div>